https://instagram.com:('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
https://twitter.com:HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000143639A41D0>, 'Connection to twitter.com timed out. (connect timeout=3)'))
https://instagram.com:HTTPSConnectionPool(host='instagram.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000256AB396D10>, 'Connection to instagram.com timed out. (connect timeout=3)'))
https://twitter.com:HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000256AB39E210>, 'Connection to twitter.com timed out. (connect timeout=3)'))
https://instagram.com response - 200
https://twitter.com response - 200
ERROR https://instagram.com response - 200
ERROR https://twitter.com response - 200
ERROR https://instagram.com NO CONNECTION
ERROR https://twitter.com NO CONNECTION
